### ISSUE TITLE
 502 Bad Gateway.  connect() failed (111: Connection refused) while connecting to upstream

### ISSUE THREAD

**Issue by hebertsonm** [hebertsonm/blog-assignment#3]
After deploying from master as described in README, I'm not able to access my services via ingress routes. The message '502 Bad Gateway' is shown on Chrome.

The following error message is found in nginx-ingress-controller log file by the command ` kubectl logs jaunty-hydra-nginx-ingress-controller-6fc94644bd-z48nk -n kube-system`

[error] 192#192: *9544 connect() failed (111: Connection refused) while connecting to upstream, client: 69.XX.XX.162, server: blogea.westus2.cloudapp.azure.com, request: "GET /blog/api/post HTTP/1.1", upstream: "http://10.244.0.69:5000/api/post", host: "blogea.westus2.cloudapp.azure.com"

My Ingress looks like:
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blogea
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: blogea.westus2.cloudapp.azure.com
    http:
      paths:
      - path: /blog(/|$)(.*)
        backend:
          serviceName: blogea
          servicePort: 80
```

I am sure the service is working. It was tested via `port-forward` and node exposure. In both tests, I got the expected answer from '/api/post' which is '[]'.
` kubectl port-forward service/blogea 8080:80` , then access it via `http://localhost:8080/api/post`
or
` kubectl expose deployment blogea --type=LoadBalancer --name=lb-blog` , then access it via `http://<external-ip>:5000/api/post`

reference:
https://kubernetes.github.io/ingress-nginx/examples/rewrite/
